package com.industrialhub.backend.common.domain;

public enum AuditAction {
    IMPORT_CREATED,
    NC_CREATED,
    NC_STATUS_CHANGED,
    ACTION_CREATED,
    ACTION_COMPLETED,
    WORK_ORDER_CREATED,
    WORK_ORDER_STATUS_CHANGED,
    EQUIPMENT_CREATED,
    EQUIPMENT_DELETED,
    LOGIN_FAILED,
    USER_CREATED,
    USER_DEACTIVATED,
    PASSWORD_CHANGED,
    RCA_CREATED,
    RCA_UPDATED,
    SUPPLIER_CREATED,
    SUPPLIER_DEACTIVATED,
    SCHEDULE_CREATED,
    SCHEDULE_DEACTIVATED,
    ROLE_CHANGED,
    USER_REACTIVATED,
    SUPPLIER_UPDATED,
    SCHEDULE_UPDATED,
    DOWNTIME_CREATED,
    DOWNTIME_DELETED,
    DOWNTIME_UPDATED,
    ALERT_EVALUATED_MANUAL,
    // US-090 SEC-065
    SHIFT_CREATED,
    SHIFT_UPDATED,
    SHIFT_DEACTIVATED,
    // US-049 AC#9
    PART_CREATED,
    PART_STOCK_ADJUSTED,
    // US-050 AC#6
    PART_CONSUMED,
    PART_CONSUMPTION_REMOVED,
    // US-059
    ATTACHMENT_UPLOADED,
    ATTACHMENT_DELETED,
    // US-061 — SLA Rules
    SLA_RULE_CREATED,
    SLA_RULE_UPDATED,
    SLA_RULE_DELETED,
    // US-062 — Escalation
    SLA_BREACHED
}
