spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/industrial_hub
spring.datasource.username=hub_user
spring.datasource.password=hub_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server
server.port=8080