package com.industrialhub.backend.common.auth.domain;

public enum AppModule {
    OEE, QMS, MAINTENANCE, PRODUCTION, TRAINING, CHANGES, MANAGEMENT_REVIEW,
    DYNAMICS_PRODUCTS, DYNAMICS_BOM, DYNAMICS_CYCLE_TIMES, DYNAMICS_STOCK, DYNAMICS_ORDERS, DYNAMICS_OEE
}
